version: '3.8'

services:
  gateway:
    build: ./gateway-service
    ports:
      - "80:80"
    depends_on:
      - auth
      - frontend
    networks:
      - microservice_network

  frontend:
    build: ./frontend-service
    networks:
      - microservice_network

  auth:
    build: ./auth-service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@auth-db:5432/auth_db
      - SECRET_KEY=your_secret_key_here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - auth-db
    volumes:
      - ./auth-service/app:/app/app
    networks:
      - microservice_network

  auth-db:
    image: postgres:17.4-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservice_network

volumes:
  postgres_data:

networks:
  microservice_network:
    driver: bridge
