services:
  gateway:
    build: ./gateway-service
    ports:
      - "80:80"
    depends_on:
      - auth
      - frontend
    networks:
      - microservice_network

  frontend:
    build: ./frontend-service
    networks:
      - microservice_network

  auth:
    build: ./auth-service
    ports:
      - "8000:8000"
    env_file:
      - ./auth-service/.env
    environment:
      - DATABASE_URL=postgresql://user:password@auth-db:5432/auth_db
    depends_on:
      auth-db:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./auth-service/app:/app/app
    networks:
      - microservice_network

  auth-db:
    image: postgres:17.4-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservice_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  microservice_network:
    driver: bridge
